### ISSUE TITLE
KeyError:'metrics'

### ISSUE THREAD

**Issue by NihaHoney** [sismetanin/emosense-semeval2019-task3-emocontext#6]
121/121 [==============================] - ETA: 0s - loss: 0.7658 - acc: 0.6902Traceback (most recent call last):
  File "Jarvis.py", line 208, in <module>
    history = model.fit([message_first_message_train, message_second_message_train, message_third_message_train],
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1137, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\keras\callbacks.py", line 416, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "C:\Users\DELL\anaconda3\lib\site-packages\kutilities\callbacks.py", line 103, in on_epoch_end
    self.add_predictions(data if len(data) > 1 else data[0], name=name,
  File "C:\Users\DELL\anaconda3\lib\site-packages\kutilities\callbacks.py", line 98, in add_predictions
    self.params['metrics'].append(entry)
KeyError: 'metrics'

@sismetanin 

Iam getting this error, please help me

**Comment by mv-uni-2021** [comment]
Hi! Were you able to find a solution to this? I have the same issue. Please share your solution if possible, thanks!
